name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  id-token: write # for OIDC trusted publisher for NPM
  contents: write # for making commits
  packages: write # for pushing to GHCR

defaults:
  run:
    working-directory: demo

jobs:
#  test:
#    runs-on: ubuntu-latest
#    # environment for review?
#    steps:
#      - uses: actions/checkout@v4
#      - uses: pnpm/action-setup@v4
#        name: Install pnpm
#        with:
#          version: 10
#          run_install: false
#      - name: Install Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'pnpm'
#          cache-dependency-path: 'demo/pnpm-lock.yaml'
#      - name: Install dependencies
#        run: pnpm install
#      - name: Run type check
#        run: pnpm types
#      - name: Run tests
#        run: pnpm test
#      # deploy to staging for review?
  get_version:
    if: github.event.push.user.login != 'GitHub Actions'
    runs-on: ubuntu-latest
#    needs: test
    outputs:
      bump: ${{ steps.version.outputs.bump }}
    steps:
      - uses: actions/checkout@v4
      - uses: jveldboom/action-conventional-versioning@v1
        id: version

  publish_npm:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - name: Bump version
        run: pnpm version ${{ needs.get_version.outputs.bump }} --git-tag-version false
      - name: Publish to NPM
        run: pnpm publish --no-git-checks

  publish_docker:
    runs-on: ubuntu-latest
    needs: get_version
    outputs:
      NEW_VERSION: ${{ steps.bump_version.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Bump version
        id: bump_version
        run: echo "NEW_VERSION=$(pnpm version ${{ needs.get_version.outputs.bump }} --git-tag-version false)" >> "$GITHUB_OUTPUT"
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/jamiefeiss/prezui-demo-test
          tags: |
            type=semver,pattern={{version}},value=${{ steps.bump_version.outputs.NEW_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.bump_version.outputs.NEW_VERSION }}
            type=semver,pattern={{major}},value=${{ steps.bump_version.outputs.NEW_VERSION }}
            type=raw,value=latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: demo
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
  release:
    runs-on: ubuntu-latest
    needs: [publish_npm, publish_docker]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Bump version
        run: pnpm version ${{ needs.publish_docker.outputs.NEW_VERSION }} --git-tag-version false
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      - name: Commit & push changes with tag
        run: |
          git add -A
          git commit -m "chore: release ${{ needs.publish_docker.outputs.NEW_VERSION }}"
          git tag ${{ needs.publish_docker.outputs.NEW_VERSION }}
          git push origin && git push --tags
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.publish_docker.outputs.NEW_VERSION }}
          generate_release_notes: true
