name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  id-token: write # for OIDC trusted publisher for NPM
  contents: write # for making commits
  packages: write # for pushing to GHCR

defaults:
  run:
    working-directory: demo

jobs:
#  test:
#    runs-on: ubuntu-latest
#    # environment for review?
#    steps:
#      - uses: actions/checkout@v4
#      - uses: pnpm/action-setup@v4
#        name: Install pnpm
#        with:
#          version: 10
#          run_install: false
#      - name: Install Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'pnpm'
#          cache-dependency-path: 'demo/pnpm-lock.yaml'
#      - name: Install dependencies
#        run: pnpm install
#      - name: Run type check
#        run: pnpm types
#      - name: Run tests
#        run: pnpm test
#      # deploy to staging for review?
  get_version:
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - uses: actions/checkout@v4
      # get new version from conventional commits & output version
      - uses: jveldboom/action-conventional-versioning@v1
        id: version
      - name: Print current version
        run: echo "${{ steps.version.outputs.previous-version }}"
      - name: Print next version
        run: echo "${{ steps.version.outputs.version }}"
#  publish_npm:
#    runs-on: ubuntu-latest
#    needs: get_version
#    steps:
#    # set new version
#    # publish to NPM
#  publish_docker:
#    runs-on: ubuntu-latest
#    needs: get_version
#    steps:
#    # set new version
#    # publish to GHCR
#  release:
#    runs-on: ubuntu-latest
#    needs: [publish_npm, publish_docker]
#    steps:
#    # create commit & tag with new version
#    # create release